### ISSUE TITLE
Marker Types and Marker List pages are blank; thumbnails don't show up on Archive page

### ISSUE THREAD

**Issue by IXthehermit** [Ayemae/Grawlix-Webcomic-CMS#10]
Similar to the recently closed issue(?), when I click on "Marker types" or "Marker list" in the admin panel, it goes to a blank page. I'm not sure when they stopped working - I haven't had to make or edit any markers since last year sometime. My "Edit Book Info" page works fine. I tried the fix listed in the other thread, but it didn't help.

This may be a separate issue, but setting the archive page to use thumbnail images isn't working, either. It claims to have generated them when I click the "generate archive thumbnails" button, but they don't show up on the archive page (and when I set page metadata to only thumbnails, the archive page doesn't seem to be listing the pages at all).

Do you have any ideas as to what's going on, with either of these?

**Comment by eishiya** [comment]
What PHP version are you using?

When you say you tried the fix in the other thread, do you mean you grabbed all the new code that's updated for PHP8, or just the small part highlighted in that thread? The Marker Types and Marker List pages work on my install, which is running the latest code.

I tested thumbnail display in archives, and it seems to work for me. My custom theme doesn't support that feature so I had to change themes to get them to show up, could that be the same problem you have? I only tested by manually generating a thumbnail though, I haven't tested the bulk thumbnail generation since I don't want to clutter my files. Would you mind checking if generating 1-2 pages' thumbnails manually (on their Edit pages) makes any difference? If it does, then it's possible the archive code is fine, and it's the bulk generation that's broken.

In the future, please open separate issues for different problems, it's easier to keep track of them that way, even if the issues might end up related.
