### ISSUE TITLE
Show marker titles on comic pages?

### ISSUE THREAD

**Issue by captainharrie** [Ayemae/Grawlix-Webcomic-CMS#14]
I've no experience with PHP before today but I've given it a good poke about and I can see with the way markers are set up this is not a particularly simple thing to implement as, currently while it is possible to call the marker ID for a page, it only applies identifiable information to the page that has been marked and doesn't carry to the subsequent pages in that chapter... so I believe you'd have to make it so that pages will inherit marker information from the most recently marked pages for this to work?

But regardless, it would be nice if it was possible to call something like `<?=show('1_marker_title' ?>`, with the number being the level for the marker being called! While I'm only personally interested in the chapter title, it would then be possible to also call scenes which would allow for something like this:
![image](https://github.com/Ayemae/Grawlix-Webcomic-CMS/assets/54632985/7209c9f0-9e08-48d1-9624-af99eb417a03)
And overall it'd just give a little more customisability. Particularly if the marker ID is accessible on all pages, I know there's a few comics hosted on comicfury which take advantage of chapter IDs to change the appearance of the site as you read, and others change what information is available on things like cast pages based on where in the story you access the page from, and probably other things too!

---

Lil more musing about the topic & why I think it'd be beneficial:

I've noticed actually, looking around at people's grawlix managed comics, not a single comic I've looked at displays the current page title on the page at all. I've a feeling the reason for this is that "Page 1" or "001" up at the top of the page is simply too short to display as a title on its own and unless the comic is posting long pages which are essentially chapters themselves it's rare for people to give pages a unique name beyond its numerical value, so the natural thing to do is to include the chapter title in front of it to create a longer and more complete title. But this isn't possible with grawlix unlike with free hosts like comicfury, so it seems like everyone simply gives up and removes the title altogether to avoid an awkwardly short title!

As a workaround one could name each individual page `Chapter One - Page 003.png` before uploading them, but if you've already uploaded your pages or you decide to go from "chapter one" to named chapters later down the line, you'll have to rename every single page one at a time in the control panel. Also, for me, I use CSP and batch export my pages, and if I include a text prefix in the name it'll export as `Precipitation_002.png` with an underscore. I can easily write a batch script to fix this personally speaking, but your average user doesn't really know how to do that or gets intimidated by more complicated things and is more likely going to not bother and just export as `002.png` The vast majority of people start with their comic on a free host, too, so they probably already have a naming convention set up for their files and again won't know an efficient way to rename things en masse. So, people are just opting to get rid of the title altogether for the sake of ease.

It's a shame, because as a reader I much prefer being able to see page numbers and what chapter we're on, as otherwise the entire comic just runs together as one big mass and I'm not able to divide the story up into processable chunks... meaning if I want to reread a particular part of the story I'll have a hard time remembering what chapter it happened in, so it's very difficult to navigate the archive. So as a creator, I'd very much like to be able to indicate this clearly to my readers!

**Comment by eishiya** [comment]
While I don't need this myself because my chapters only have numeric names and I include those numbers in the page titles (e.g. "2.05" for chapter 2, page 5), I think this is a good idea :D

`<?=show('1_marker_title' ?>` (or rather, for consistency, probably `<?=show('marker_title_1' ?>`) should be doable. However, it would require extra queries to find all the marker(s) which are relevant to that page. All the `show` items are pre-fetched, i.e. they always exist even if you don't use them, which means these extra queries will have a performance hit even for those users who never display markers. I'm not entirely comfortable with that, but hopefully it will not be a very noticeable impact. We can benchmark the impact and make this marker fetching opt-in if it turns out heavy, I guess :D

This is how I'd implement it:

The page info is currently populated in `_system/GrlxPage2_Comic.php` in `getComicPage()`. There, it does a query on the `book_page` table for all the various things. Images are stored in another table and fetched in a different method. This includes a `marker_id`, but obviously this only means anything for those pages that have a marker, and not for the pages between markers.
Then, we would need to query `marker_types` for a list of marker types, sorted by rank. Then, for each rank, query `book_page LEFT JOIN marker ON book_page.marker_id = marker.id` where `marker.marker_type_id` is equal to the each marker type and `book_page.sort_order` is less than or equal to the current page's sort order. If we order by sort_order descending and get the first result, that'll give us the first page before the current page that has a marker of the given rank, and we can get its `marker.title` (which we should have thanks to the left join) as `marker_title_<rank>`.
This approach requires N+1 extra queries, where N is the number of marker types the comic has.

Perhaps someone better with SQL can recommend a some JOIN magic to turn this into just one single extra query where we join `book_page`, `marker`, *and* `marker_type`, so that we don't have to iterate over marker types by PHP and can instead get a list of all markers relevant to the current page somehow. And if no one has a better suggestion, I can try implementing it as described above. ~~The hardest part is building the queries using the database interface Grawlix uses.~~

**Comment by eishiya** [comment]
I've implemented this in my local copy, so it's definitely doable :D! So far I'm using the N+1 queries approach, but I'm still willing to look into a single-query approach if someone points me in the right direction.

I've also made it cut off child markers on each parent marker, something I forgot to mention in my previous comment.

Benchmarking it, it takes about 2ms to fetch all the marker information in my set up which has only two marker types, of which only one is used. For comparison, fetching all the other comic page data including the second query for images on this same set-up, takes about 3-4ms. So, while not *slow*, it is a significant chunk of time in comparison, about 50% more load time for each marker type you have.

Some questions:
1. How do you feel about this performance?
2. Should we also expose the marker *type* name (e.g. "Chapter", "Scene")? This should have a negligible performance impact, as it's just getting an extra field when fetching the list of marker types.

Also, you mentioned using the chapter to enable different styling on ComicFury. Grawlix supports this sort of thing already with its multi-theme feature, so you should not need to use marker names for this. When multi-theme is enabled, you should be able to select a theme/tone for each marker in the admin panel, or something like that - I haven't used it myself yet.

**Comment by captainharrie** [comment]
Oh wow! Thank you for doing this so quickly :) That all sounds fine to me! (And neat to know about the built in theme stuff! It's not something I'd personally use so I had not actually checked, but just was something I remembered when I saw you can get the ID), 

And I think there's probably no harm in adding marker type if there was a desire to release a new theme that takes advantage of this so that there's no predefined assumptions about the marker language, but otherwise I think people are more likely to just write them themselves while they do their customising if they need to, i.e writing `Chapter <?=show('marker_title_1') ?>`, which would always be correct because it's before that specific rank of marker!

**Comment by eishiya** [comment]
I've added `marker_type_<rank>` as well now :D

It may take a while for my PR to be reviewed and added to this main repo as Ayemae's quite busy, but you if you're not afraid of using unreviewed code, you can download the single modified file from my fork (https://github.com/eishiya/Grawlix-Webcomic-CMS/blob/show_markers/grawlix-cms/_system/GrlxPage2_Comic.php) or from the PR.

One last thing: Unlike the other show() items, these are only populated if they actually exist, so they may be unset. For example, if you have Chapters (rank 1) and Scenes (rank 2), a page that starts a new Chapter will not be part of any Scene, and trying to output its Scene may result in a PHP error because you're trying to print the value of a non-existent variable. To avoid such errors, you should check that the marker type/title actually exists. The most compact way to do this is with the null coalescing operator `??` and an empty alternative, e.g.
```php
<?=show('marker_title_1')??''?>
```
This means "if `show('marker_title_1')` is not empty, use it, but if it is empty, show `''` (an empty string) instead".

If you're using both marker_title_N and marker_type_N, you should only need to check one of them, e.g.
```php
<?=isset(show('marker_title_1'))? '<h2>'.show('marker_type_1').': '.show('marker_title_1').'</h2>' : '' ?>
```
This'll show e.g. `<h2>Chapter: In Which an Example is Made</h2>` or nothing at all if the page isn't part of any chapter,

**Comment by captainharrie** [comment]
Thank you very much! I won't be launching my comic until next year so I'm just fiddling in advance to get things ready for that so I'm more than happy to give your code a whirl, thank you again for putting this together for me! :)
