### ISSUE TITLE
Deleting comic pages breaks the nav links; updating page order to remove the gap causes "Page Not Found" errors

### ISSUE THREAD

**Issue by IXthehermit** [Ayemae/Grawlix-Webcomic-CMS#20]
I deleted some old filler art pages, but the "next page" link on the comic before the deleted pages still points to the address of the first deleted page (in this case, /comic/621 still expecting /comic/622 to be next, when the next page should be /626), and leads to a Page Not Found error page.

I tried updating the order numbers of the next few pages, so that /626 would be /622 and so on, but the link from /621 still led to an error page. So I set the order numbers back to what they were before, and now their original addresses lead to Page Not Found errors, too. The page still exists in the Grawlix backend and can be edited, but the live page's address doesn't work, and the Back/Next links at the top of the Edit Comic page are grayed out, so to speak.

The page before the deleted pages: https://www.tamurancomic.com/comic/621
(that one's still filler that I want to delete from the archive; I just haven't yet)
The page that should come after the deleted pages, but after changing the order doesn't exist: https://www.tamurancomic.com/comic/626
The next page that's actually working after the ones whose order numbers were changed: https://www.tamurancomic.com/comic/631

I'll attach a screenshot of the current Book View, just in case it's helpful for showing what "order numbers" I'm talking about. 
![image](https://github.com/Ayemae/Grawlix-Webcomic-CMS/assets/8828711/e3984dcc-7db2-4a86-92f9-78f5870510a7)

Any help would be very much appreciated.

**Comment by IXthehermit** [comment]
oh, and I'm using Grawlix 1.6.0 and may not have downloaded any more recent small file updates, but a friend who just created their comic site using the latest files said they were having the same issue when they deleted pages.

**Comment by eishiya** [comment]
1.6.0 is a sort of prerelease version we made available because 1.5 was incompatible with modern PHP, it's likely there are still some bugs, possibly stemming from the PHP changes.

Normally, when you update the sort order (by deleting pages, or using the Sort button after changing the page sort numbers), all the sort numbers should get *reassigned* to start at 1 and increase by 1 with each page, so what is currently "626" should become "622" and so on. This is why the next link on page 621 points to 622 - normally, that page should exist. So, it's very odd that apparently this doesn't happen automatically, and even weirder that *manually* adjusting these numbers to be correct does not work.

The problem seems to be that the function `reset_page_order` isn't working correctly. This is why deleting pages causes gaps *and* why trying to fix them manually doesn't work - manually adjusted numbers have "0.001" added to them to ensure consistent sorting when inserting pages between others, or when giving the same pages the same sort order, allowing them to preserve their current relative order. Normally, `reset_page_order` gets rid of that decimal component, but in this case it's not, so when you manually set a page to have order `622` it actually ends up as an uncorrected `622.0010`, which is not equal to `622` so it doesn't get found when your site tries to display page `622`.

It looks like when `reset_page_order` fetches the list of pages to update, it gets nothing back. I will look into why that is. Thanks for reporting this!

**Comment by eishiya** [comment]
You should be able to replace /_admin/book.view.php with this new version to fix the issue. After uploading it, navigate to the Book View and click "Sort", and it should update all the sort orders correctly. Please let your friend know as well!
https://github.com/eishiya/Grawlix-Webcomic-CMS/blob/master/grawlix-cms/_admin/book.view.php

Thanks again for reporting this bug! It's a big one that crept up due to the underlying language changing rather than through changes in the code.

**Comment by IXthehermit** [comment]
It's working now - thank you so much! Thanks also for taking the time to write out the explanation of what was going on (I know next to nothing about php, but it's good to learn. I wondered if the recent php changes had something to do with this one)
