### ISSUE TITLE
Error - posts no longer adding comic image files

### ISSUE THREAD

**Issue by IXthehermit** [Ayemae/Grawlix-Webcomic-CMS#26]
Hello!
Last night I tried making a comic update post, but selected multiple image files in the file explorer... which I now gather you are not supposed to do, whoops. Grawlix created the post, but gave me an "Unable to upload image. Looks like a folder permissions problem" error and didn't attach any images to it. I tried again, selecting only the first image instead, but now it won't upload images at all - it creates the post with no image. If I check assets/images/comics in the FTP, it's not creating the folder for the new post image and thumbnail to go into, either. Would you be able to tell me what I broke/how I might be able to fix it?

**Comment by eishiya** [comment]
Uploading multiple images should not cause any problems, that's why the file picker allows it. Grawlix creates a multi-image page in that case, which is useful for long-scroll comics, etc.

Have you checked the folder permissions, since that's what the error said? It seems unlikely that uploading multiple files would break anything or cause folder permissions to change, but it's possible, or perhaps something changed between your last successful update and this one - for example, perhaps your web host changed what user PHP runs as, requiring different permissions, or perhaps they updated the server, which may reset folder permissions if they're not careful. You should be able to check/set permissions via your FTP client. On my server, the Owner having full permissions seems to be enough, but if PHP runs as a different user, it's possible you may need to set Other/Public to allow Write as well.

**Comment by IXthehermit** [comment]
Permissions for /assets, /images, /comics, and all the page folders inside that one are all still set to 755; I don't see anything that might have changed there... but it wouldn't be the first time our host changed server settings without telling anyone. This evening I tried to upload a file via ftp (to fix the time zone issue after reading the other threads here, incidentally), and Filezilla wouldn't overwrite the old file - it's giving "could not start transfer" as the reason the upload failed. I'll ask around and see what I can find out. Thanks very much for the insight.

**Comment by eishiya** [comment]
755 means only the Owner can write, Other can't, so if PHP isn't running as the Owner, that could pose a problem. Just in case, try 777 - everyone can read, write, and execute. If even that doesn't work, then the problem isn't actually the permissions (in that case, put it back to 755, it would be a bad idea to leave 777 if you don't need it).

If you're having trouble overwriting files, that also suggests some sort of write issue, and it could be related. I can't help with this sysadmin stuff. I'd suggest waiting until you've got that sorted out before you try to figure out what's going on with Grawlix, since it could just be the same issue. So, don't do the 777 thing just yet.

**Comment by IXthehermit** [comment]
Now that we've got it sorted out... it turned out to be a server issue where another site had errored and filled up the server with debug logs. Grawlix couldn't upload the image because there was no space for it. 

Thank you for helping us start to figure out the problem!

**Comment by IXthehermit** [comment]
Now that we've got it sorted out... it turned out to be a server issue where another site had errored and filled up the server with debug logs. Grawlix couldn't upload the image because there was no space for it.

Thank you for helping us start to figure out the problem!
